<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Old test/nashorn/script/basic/NASHORN-215.js</title>
    <link rel="stylesheet" href="../../../../style.css" />
  </head>
  <body>
    <pre>
  1 /*
  2  * Copyright (c) 2010, 2013, Oracle and/or its affiliates. All rights reserved.
  3  * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  4  *
  5  * This code is free software; you can redistribute it and/or modify it
  6  * under the terms of the GNU General Public License version 2 only, as
  7  * published by the Free Software Foundation.
  8  *
  9  * This code is distributed in the hope that it will be useful, but WITHOUT
 10  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 11  * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 12  * version 2 for more details (a copy is included in the LICENSE file that
 13  * accompanied this code).
 14  *
 15  * You should have received a copy of the GNU General Public License version
 16  * 2 along with this work; if not, write to the Free Software Foundation,
 17  * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 18  *
 19  * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 20  * or visit www.oracle.com if you need additional information or have any
 21  * questions.
 22  */
 23 
 24 /**
 25  * NASHORN-215 : Exception parameter should be local to the catch block.
 26  *
 27  * @test
 28  * @run
 29  */
 30 
 31 var exp = new Error(&quot;Error!&quot;);
 32 try {
 33    throw exp;
 34 } catch (e) {
 35    print(&quot;1 &quot; + e.message);
 36    try {
 37       throw new Error(&quot;Nested error&quot;);
 38    } catch (e) {
 39       print(&quot;2 &quot; + e.message);
 40    }
 41    print(&quot;3 &quot; + e.message);
 42 };
 43 
 44 try {
 45    print(e);
 46    print(&quot;should not reach here&quot;);
 47 } catch (e1) {
 48    print(&quot;4 success&quot;);
 49 }
 50 
 51 function f() {
 52     var x = 4;
 53     try {
 54        throw exp;
 55     } catch (e) {
 56        print(&quot;5 &quot; + e.message);
 57        (function() {
 58            try {
 59               throw new Error(&quot;Nested error.&quot;);
 60            } catch (e) {
 61               try {
 62                 print(&quot;6 &quot; + e.message);
 63                 throw new Error(&quot;error in catch&quot;);
 64               } catch (e) {
 65                  print(&quot;7 &quot; + e.message);
 66               }
 67               (function() { print(&quot;8 &quot; + e.message); })();
 68               print(&quot;9 &quot; + e.message);
 69            }
 70           print(&quot;a &quot; + e.message);
 71        })();
 72        print(&quot;b &quot; + e.message);
 73     };
 74     return function() { return x; }();
 75 }
 76 f();
 77 
 78 try {
 79   throw &quot;asdf1&quot;;
 80 } catch (ex) {
 81   (function() {
 82     var o = {};
 83     with (o) {
 84       print(ex);
 85     }
 86   })();
 87   try {
 88     throw &quot;asdf2&quot;;
 89   } catch (ex) {
 90     (function() {
 91       var o = {};
 92       with (o) {
 93         print(ex);
 94         ex = &quot;asdf3&quot;;
 95       }
 96     })();
 97     print(ex);
 98   }
 99   print(ex);
100 }
    </pre>
  </body>
</html>