<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Frames src/hotspot/share/utilities/exceptions.hpp</title>
    <link rel="stylesheet" href="../../../../style.css" />
    <script type="text/javascript" src="../../../../navigation.js"></script>
  </head>
<body onkeypress="keypress(event);">
<a name="0"></a>
<hr />
<pre>  1 /*
  2  * Copyright (c) 1998, 2020, Oracle and/or its affiliates. All rights reserved.
  3  * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
  4  *
  5  * This code is free software; you can redistribute it and/or modify it
  6  * under the terms of the GNU General Public License version 2 only, as
  7  * published by the Free Software Foundation.
  8  *
  9  * This code is distributed in the hope that it will be useful, but WITHOUT
 10  * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 11  * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 12  * version 2 for more details (a copy is included in the LICENSE file that
 13  * accompanied this code).
 14  *
 15  * You should have received a copy of the GNU General Public License version
 16  * 2 along with this work; if not, write to the Free Software Foundation,
 17  * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 18  *
 19  * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 20  * or visit www.oracle.com if you need additional information or have any
 21  * questions.
 22  *
 23  */
 24 
 25 #ifndef SHARE_UTILITIES_EXCEPTIONS_HPP
 26 #define SHARE_UTILITIES_EXCEPTIONS_HPP
 27 
 28 #include &quot;memory/allocation.hpp&quot;
 29 #include &quot;oops/oopsHierarchy.hpp&quot;
 30 #include &quot;utilities/ostream.hpp&quot;
 31 #include &quot;utilities/sizes.hpp&quot;
 32 
 33 // This file provides the basic support for exception handling in the VM.
 34 // Note: We do not use C++ exceptions to avoid compiler dependencies and
 35 // unpredictable performance.
 36 //
 37 // Scheme: Exceptions are stored with the thread. There is never more
 38 // than one pending exception per thread. All functions that can throw
 39 // an exception carry a THREAD argument (usually the last argument and
 40 // declared with the TRAPS macro). Throwing an exception means setting
 41 // a pending exception in the thread. Upon return from a function that
 42 // can throw an exception, we must check if an exception is pending.
 43 // The CHECK macros do this in a convenient way. Carrying around the
 44 // thread provides also convenient access to it (e.g. for Handle
 45 // creation, w/o the need for recomputation).
 46 
 47 
 48 
 49 // Forward declarations to be independent of the include structure.
 50 
 51 class Thread;
 52 class Handle;
 53 class Symbol;
 54 class JavaCallArguments;
 55 class methodHandle;
 56 
 57 // The ThreadShadow class is a helper class to access the _pending_exception
 58 // field of the Thread class w/o having access to the Thread&#39;s interface (for
 59 // include hierachy reasons).
 60 
 61 class ThreadShadow: public CHeapObj&lt;mtThread&gt; {
 62   friend class VMStructs;
 63   friend class JVMCIVMStructs;
 64 
 65  protected:
 66   oop  _pending_exception;                       // Thread has gc actions.
 67   const char* _exception_file;                   // file information for exception (debugging only)
 68   int         _exception_line;                   // line information for exception (debugging only)
 69   friend void check_ThreadShadow();              // checks _pending_exception offset
 70 
 71   // The following virtual exists only to force creation of a vtable.
 72   // We need ThreadShadow to have a vtable, even in product builds,
 73   // so that its layout will start at an offset of zero relative to Thread.
 74   // Some C++ compilers are so &quot;clever&quot; that they put the ThreadShadow
 75   // base class at offset 4 in Thread (after Thread&#39;s vtable), if they
 76   // notice that Thread has a vtable but ThreadShadow does not.
 77   virtual void unused_initial_virtual() { }
 78 
 79  public:
 80   oop  pending_exception() const                 { return _pending_exception; }
 81   bool has_pending_exception() const             { return _pending_exception != NULL; }
 82   const char* exception_file() const             { return _exception_file; }
 83   int  exception_line() const                    { return _exception_line; }
 84 
 85   // Code generation support
 86   static ByteSize pending_exception_offset()     { return byte_offset_of(ThreadShadow, _pending_exception); }
 87 
 88   // use THROW whenever possible!
 89   void set_pending_exception(oop exception, const char* file, int line);
 90 
 91   // use CLEAR_PENDING_EXCEPTION whenever possible!
 92   void clear_pending_exception();
 93 
 94   ThreadShadow() : _pending_exception(NULL),
 95                    _exception_file(NULL), _exception_line(0) {}
 96 };
 97 
 98 
 99 // Exceptions is a helper class that encapsulates all operations
100 // that require access to the thread interface and which are
101 // relatively rare. The Exceptions operations should only be
102 // used directly if the macros below are insufficient.
103 
104 class Exceptions {
105   static bool special_exception(Thread *thread, const char* file, int line, Handle exception);
106   static bool special_exception(Thread* thread, const char* file, int line, Symbol* name, const char* message);
107 
108   // Count out of memory errors that are interesting in error diagnosis
109   static volatile int _out_of_memory_error_java_heap_errors;
110   static volatile int _out_of_memory_error_metaspace_errors;
111   static volatile int _out_of_memory_error_class_metaspace_errors;
112 
113   // Count linkage errors
114   static volatile int _linkage_errors;
115  public:
116   // this enum is defined to indicate whether it is safe to
117   // ignore the encoding scheme of the original message string.
118   typedef enum {
119     safe_to_utf8 = 0,
120     unsafe_to_utf8 = 1
121   } ExceptionMsgToUtf8Mode;
122   // Throw exceptions: w/o message, w/ message &amp; with formatted message.
123   static void _throw_oop(Thread* thread, const char* file, int line, oop exception);
124   static void _throw(Thread* thread, const char* file, int line, Handle exception, const char* msg = NULL);
125 
126   static void _throw_msg(Thread* thread, const char* file, int line, Symbol* name, const char* message);
127   static void _throw_msg(Thread* thread, const char* file, int line, Symbol* name, const char* message,
128                          Handle loader, Handle protection_domain);
129 
130   static void _throw_msg_cause(Thread* thread, const char* file, int line, Symbol* name, const char* message, Handle h_cause);
131   static void _throw_msg_cause(Thread* thread, const char* file, int line, Symbol* name, const char* message, Handle h_cause,
132                                Handle h_loader, Handle h_protection_domain);
133 
134   static void _throw_cause(Thread* thread, const char* file, int line, Symbol* name, Handle h_cause);
135   static void _throw_cause(Thread* thread, const char* file, int line, Symbol* name, Handle h_cause,
136                            Handle h_loader, Handle h_protection_domain);
137 
138   static void _throw_args(Thread* thread, const char* file, int line,
139                           Symbol* name, Symbol* signature,
140                           JavaCallArguments* args);
141 
142   // There is no THROW... macro for this method. Caller should remember
143   // to do a return after calling it.
144   static void fthrow(Thread* thread, const char* file, int line, Symbol* name,
145                      const char* format, ...) ATTRIBUTE_PRINTF(5, 6);
146 
147   // Create and initialize a new exception
148   static Handle new_exception(Thread* thread, Symbol* name,
149                               Symbol* signature, JavaCallArguments* args,
150                               Handle loader, Handle protection_domain);
151 
152   static Handle new_exception(Thread* thread, Symbol* name,
153                               Symbol* signature, JavaCallArguments* args,
154                               Handle cause,
155                               Handle loader, Handle protection_domain);
156 
157   static Handle new_exception(Thread* thread, Symbol* name,
158                               Handle cause,
159                               Handle loader, Handle protection_domain,
160                               ExceptionMsgToUtf8Mode to_utf8_safe = safe_to_utf8);
161 
162   static Handle new_exception(Thread* thread, Symbol* name,
163                               const char* message, Handle cause,
164                               Handle loader, Handle protection_domain,
165                               ExceptionMsgToUtf8Mode to_utf8_safe = safe_to_utf8);
166 
167   static Handle new_exception(Thread* thread, Symbol* name,
168                               const char* message,
169                               ExceptionMsgToUtf8Mode to_utf8_safe = safe_to_utf8);
170 
171   static void throw_stack_overflow_exception(Thread* thread, const char* file, int line, const methodHandle&amp; method);
172 
173   static void wrap_dynamic_exception(bool is_indy, Thread* thread);
174 
175   // Exception counting for error files of interesting exceptions that may have
176   // caused a problem for the jvm
177   static volatile int _stack_overflow_errors;
178 
179   static bool has_exception_counts();
180   static void count_out_of_memory_exceptions(Handle exception);
181   static void print_exception_counts_on_error(outputStream* st);
182 
183   // for AbortVMOnException flag
184   static void debug_check_abort(Handle exception, const char* message = NULL);
185   static void debug_check_abort_helper(Handle exception, const char* message = NULL);
186   static void debug_check_abort(const char *value_string, const char* message = NULL);
187 
188   // for logging exceptions
189   static void log_exception(Handle exception, const char* message);
190 };
191 
192 
193 // The THREAD &amp; TRAPS macros facilitate the declaration of functions that throw exceptions.
194 // Convention: Use the TRAPS macro as the last argument of such a function; e.g.:
195 //
196 // int this_function_may_trap(int x, float y, TRAPS)
197 
198 #define THREAD __the_thread__
199 #define TRAPS  Thread* THREAD
200 
201 
202 // The CHECK... macros should be used to pass along a THREAD reference and to check for pending
203 // exceptions. In special situations it is necessary to handle pending exceptions explicitly,
204 // in these cases the PENDING_EXCEPTION helper macros should be used.
205 //
206 // Macro naming conventions: Macros that end with _ require a result value to be returned. They
207 // are for functions with non-void result type. The result value is usually ignored because of
208 // the exception and is only needed for syntactic correctness. The _0 ending is a shortcut for
209 // _(0) since this is a frequent case. Example:
210 //
211 // int result = this_function_may_trap(x_arg, y_arg, CHECK_0);
212 //
213 // CAUTION: make sure that the function call using a CHECK macro is not the only statement of a
214 // conditional branch w/o enclosing {} braces, since the CHECK macros expand into several state-
215 // ments! Also make sure it is not used on a function call that is part of a return statement!
216 
217 #define PENDING_EXCEPTION                        (((ThreadShadow*)THREAD)-&gt;pending_exception())
218 #define HAS_PENDING_EXCEPTION                    (((ThreadShadow*)THREAD)-&gt;has_pending_exception())
219 #define CLEAR_PENDING_EXCEPTION                  (((ThreadShadow*)THREAD)-&gt;clear_pending_exception())
220 
221 #define CHECK                                    THREAD); if (HAS_PENDING_EXCEPTION) return       ; (void)(0
222 #define CHECK_(result)                           THREAD); if (HAS_PENDING_EXCEPTION) return result; (void)(0
223 #define CHECK_0                                  CHECK_(0)
224 #define CHECK_NH                                 CHECK_(Handle())
225 #define CHECK_NULL                               CHECK_(NULL)
226 #define CHECK_false                              CHECK_(false)
227 #define CHECK_JNI_ERR                            CHECK_(JNI_ERR)
228 
229 #define CHECK_AND_CLEAR                         THREAD); if (HAS_PENDING_EXCEPTION) { CLEAR_PENDING_EXCEPTION; return;        } (void)(0
230 #define CHECK_AND_CLEAR_(result)                THREAD); if (HAS_PENDING_EXCEPTION) { CLEAR_PENDING_EXCEPTION; return result; } (void)(0
231 #define CHECK_AND_CLEAR_0                       CHECK_AND_CLEAR_(0)
232 #define CHECK_AND_CLEAR_NH                      CHECK_AND_CLEAR_(Handle())
233 #define CHECK_AND_CLEAR_NULL                    CHECK_AND_CLEAR_(NULL)
234 #define CHECK_AND_CLEAR_false                   CHECK_AND_CLEAR_(false)
235 
236 // The THROW... macros should be used to throw an exception. They require a THREAD variable to be
237 // visible within the scope containing the THROW. Usually this is achieved by declaring the function
238 // with a TRAPS argument.
239 
240 #define THREAD_AND_LOCATION                      THREAD, __FILE__, __LINE__
<a name="1" id="anc1"></a>

241 
242 #define THROW_OOP(e)                                \
243   { Exceptions::_throw_oop(THREAD_AND_LOCATION, e);                             return;  }
244 
245 #define THROW_HANDLE(e)                                \
246   { Exceptions::_throw(THREAD_AND_LOCATION, e);                             return;  }
247 
248 #define THROW(name)                                 \
249   { Exceptions::_throw_msg(THREAD_AND_LOCATION, name, NULL); return;  }
250 
251 #define THROW_MSG(name, message)                    \
252   { Exceptions::_throw_msg(THREAD_AND_LOCATION, name, message); return;  }
253 
254 #define THROW_CAUSE(name, cause)   \
255   { Exceptions::_throw_cause(THREAD_AND_LOCATION, name, cause); return; }
256 
257 #define THROW_MSG_LOADER(name, message, loader, protection_domain) \
258   { Exceptions::_throw_msg(THREAD_AND_LOCATION, name, message, loader, protection_domain); return;  }
259 
260 #define THROW_ARG(name, signature, args) \
261   { Exceptions::_throw_args(THREAD_AND_LOCATION, name, signature, args);   return; }
262 
263 #define THROW_OOP_(e, result)                       \
264   { Exceptions::_throw_oop(THREAD_AND_LOCATION, e);                           return result; }
265 
266 #define THROW_HANDLE_(e, result)                       \
267   { Exceptions::_throw(THREAD_AND_LOCATION, e);                           return result; }
268 
269 #define THROW_(name, result)                        \
270   { Exceptions::_throw_msg(THREAD_AND_LOCATION, name, NULL); return result; }
271 
272 #define THROW_MSG_(name, message, result)           \
273   { Exceptions::_throw_msg(THREAD_AND_LOCATION, name, message); return result; }
274 
275 #define THROW_MSG_LOADER_(name, message, loader, protection_domain, result) \
276   { Exceptions::_throw_msg(THREAD_AND_LOCATION, name, message, loader, protection_domain); return result; }
277 
278 #define THROW_ARG_(name, signature, args, result) \
279   { Exceptions::_throw_args(THREAD_AND_LOCATION, name, signature, args); return result; }
280 
281 #define THROW_MSG_CAUSE(name, message, cause)   \
282   { Exceptions::_throw_msg_cause(THREAD_AND_LOCATION, name, message, cause); return; }
283 
284 #define THROW_MSG_CAUSE_(name, message, cause, result)   \
285   { Exceptions::_throw_msg_cause(THREAD_AND_LOCATION, name, message, cause); return result; }
286 
287 
288 #define THROW_OOP_0(e)                      THROW_OOP_(e, 0)
289 #define THROW_HANDLE_0(e)                   THROW_HANDLE_(e, 0)
290 #define THROW_0(name)                       THROW_(name, 0)
291 #define THROW_MSG_0(name, message)          THROW_MSG_(name, message, 0)
292 #define THROW_WRAPPED_0(name, oop_to_wrap)  THROW_WRAPPED_(name, oop_to_wrap, 0)
293 #define THROW_ARG_0(name, signature, arg)   THROW_ARG_(name, signature, arg, 0)
294 #define THROW_MSG_CAUSE_0(name, message, cause) THROW_MSG_CAUSE_(name, message, cause, 0)
295 #define THROW_MSG_CAUSE_NULL(name, message, cause) THROW_MSG_CAUSE_(name, message, cause, NULL)
296 
297 #define THROW_NULL(name)                    THROW_(name, NULL)
298 #define THROW_MSG_NULL(name, message)       THROW_MSG_(name, message, NULL)
299 
300 // The CATCH macro checks that no exception has been thrown by a function; it is used at
301 // call sites about which is statically known that the callee cannot throw an exception
302 // even though it is declared with TRAPS.
303 
304 #define CATCH                              \
305   THREAD); if (HAS_PENDING_EXCEPTION) {    \
306     oop ex = PENDING_EXCEPTION;            \
307     CLEAR_PENDING_EXCEPTION;               \
308     ex-&gt;print();                           \
309     ShouldNotReachHere();                  \
310   } (void)(0
311 
312 // ExceptionMark is a stack-allocated helper class for local exception handling.
313 // It is used with the EXCEPTION_MARK macro.
314 
315 class ExceptionMark {
316  private:
317   Thread* _thread;
318 
319  public:
320   ExceptionMark(Thread*&amp; thread);
321   ~ExceptionMark();
322 };
323 
324 
325 
326 // Use an EXCEPTION_MARK for &#39;local&#39; exceptions. EXCEPTION_MARK makes sure that no
327 // pending exception exists upon entering its scope and tests that no pending exception
328 // exists when leaving the scope.
329 
330 // See also preserveException.hpp for PRESERVE_EXCEPTION_MARK macro,
331 // which preserves pre-existing exceptions and does not allow new
332 // exceptions.
333 
334 #define EXCEPTION_MARK                           Thread* THREAD = NULL; ExceptionMark __em(THREAD);
335 
336 #endif // SHARE_UTILITIES_EXCEPTIONS_HPP
<a name="2" id="anc2"></a><b style="font-size: large; color: red">--- EOF ---</b>
















































































</pre>
<input id="eof" value="2" type="hidden" />
</body>
</html>